benchmarks/fptaylor-real2float.fpcore
benchmarks/fptaylor-tests.fpcore
benchmarks/rosa.fpcore
benchmarks/salsa.fpcore
benchmarks/salsa.fpimp
infra/test-core2c.rkt
tools/core2c.rkt
tools/fpcore.rkt
tools/fpimp.rkt
tools/sample-accuracy.rkt

The "Metadata" standard says that the precision should be specified in the `:precision` field, yet the benchmarks use `:type`. This changes all of the benchmarks from `:type` to `:precision`.

Converted all benchmarks

---

tools/core2scala.rkt

I added a simple check to the translation of numbers, that uses the exact integer number, in case a number like 3.0 appears in an FPCore file. Instead of producing the scala 3.0, it will now produce a 3 which the Scala compiler can parse it into an integer instead of a floating-point constant.

Make core2scala detect exact integer numbers

---

tools/daisy_herbie.py

Machine independence required many changes:
- Take Herbie and Daisy paths as arguments
- Compute FPBench path on its own
- Avoid using files as much as possible; used only for Daisy
- Output goes to standard output and standard error
There were also large style changes made:
- `subprocess.run` instead of the more complex `Popen`
- `with` to encapsulate file use with automatic closing
- Streams to split generation and output

Make daisy_herbie script machine-independent

---

tools/core2c.rkt

Previously, core2c.rkt assigned an internal type `bool (int) to all
temp variables that would be involved in a subsequent test.  This caused
miscompiliation of "Trapeze" from benchmarks/salsa.fpcore where
variables that should have been float were erroneously declared as int.
This change maintains proper type information allowing correct
comparisons.
Additionally, '_' is an allowed character in variable names that does
not need to be converted to an integer representation by fix-name.

core2c.rkt: fix bool temp variables and naming

---

tools/core2go.rkt

This is an initial implementation of an FPCore to golang compiler based
on the core2c implementation.  It produces a package with the name of
the first argument and converts types, operators and functions to their
golang equivalents.
usage:
racket core2go.rkt package_name <input.fpcore >output.go
Known issues:
- Golang's math library only accepts float64 arguments, so usage of
float32 inputs will cause an error on attempted compilation.

core2go: initial implementation of golang compiler

---

.travis.yml
Makefile
infra/test-common.rkt
infra/test-core2c.rkt
infra/test-core2js.rkt
infra/test-core2smtlib2.rkt
infra/test-imp2core.rkt
tools/core2smtlib2.rkt

Somewhat tested with Z3. Known caveats:
* Not all functions (sin, log, floor, etc.) are supported. This compiler
will thrown an error.
* Some mathematical constants are harder to compute exactly than others using
math/bigfloat, and thus are not supported. This compiler will throw an error.
* Four precisions are supported: binary16, binary32, binary64, and binary128.
* The five IEEE rounding modes are supported: nearestEven, nearestAway, toZero,
toPositive, and toNegative. Due to limitations of math/bigfloat, nearestAway
is not supported for mathematical constants.

Add FPCore to SMT-LIB compiler.

---

benchmarks.bib
benchmarks/precimonious.fpcore

This is the arclength benchmark used as an example in the FPBench 1.1 standard update proposal.
The precimonious paper examines 12 programs, including arclength - this is the only one with source readily available in the paper. It might be a good idea to port the other benchmarks as well.

add arclength benchmark

---

Makefile
infra/test-core2wls.rkt
tools/core2math.rkt
tools/core2wls.rkt

This compiler ignores all precision annotations and converts FPCores into Wolfram Language as directly as possible. Infinity and NaN from floating-point land are translated into Infinity and Indeterminate, which don't necessarily have the same behavior. This is not meant to be a rigorous translation of the subtleties of floating-point edge cases and rounding behavior, but rather a low-overhead translation of simple mathematical expressions.
This inital version of the compiler is not complete or particularly well tested. Loops will be added soon.
It is not immediately obvious how to do automated testing, as proper tests require Mathematica to be installed (and thus a Mathematica license...). There are also some potentially tricky edge cases, for example with Mathematica continuing …

FPCore to Mathematica (Wolfram Language) compiler

---

main.rkt
src/common-subexpr-elim.rkt
tools/common-subexpr-elim.rkt

This change adds a common subexpression eliminator for `FPCore`s. This will take all common subexpressions that appear more than once in the input `FPCore` and extract them out to a top-level `let` binding which will be in the output `FPCore`.

Common Subexpression Eliminator

---

Makefile
export.rkt
infra/test-core2c.rkt
infra/test-core2js.rkt
infra/test-imperative.rkt
src/compilers.rkt
src/core2c.rkt
src/core2go.rkt
src/core2js.rkt
src/core2sollya.rkt
src/imperative.rkt
src/supported.rkt
tests/sanity-constants.fpcore

Main changes:
- Common test structure (C and JS only)
- Struct for supported operators, constants, and precisions (C/Go/JS compiler)
- Invert functions for whitelist -> blacklist and vice versa (operators and constants)
- Function "valid-core", returns true if fpcore is supported by particular compiler
- Test flags
- "-q or --quiet": No output unless test failure
- "-v or --verbose": Output regardless of success/failure
- "--exact-output": Output straight from compiler without conversion to number (useful for Sollya)
- "--very-verbose": Both verbose and exact-output flags
Minor changes:
- C, Go, JS now compile operator arguments in their respective files rather than common compiler
- Makefile no longer uses unsupported or precisions (C and JS only)
- js-runtime parameter reimplemented …

Common test structure for C/JS and common supported struct for C/JS/Go compiler

---

src/canonicalizer.rkt
src/fpcore-visitor.rkt
transform.rkt

Add a reusable visitor template to make it easier to write some FPCore AST passes and analyses. Also use it to implement new annotation canonicalizer and condenser, and provide support for them from transform.rkt.

Fpcore visitor

---

Makefile
infra/bench-stats.rkt
infra/core2json.rkt
infra/gen-expr.rkt
infra/gen-tests.rkt
infra/test-common.rkt
main.rkt
src/common.rkt
src/compilers.rkt
src/core2c.rkt
src/core2cml.rkt
src/core2fptaylor.rkt
src/core2gappa.rkt
src/core2go.rkt
src/core2js.rkt
src/core2scala.rkt
src/core2smtlib2.rkt
src/core2sollya.rkt
src/core2tex.rkt
src/core2wls.rkt
src/fpcore-interpreter.rkt
src/fpcore-reader.rkt
src/fpcore-visitor.rkt
src/imperative.rkt
src/supported.rkt
tests/sanity/constants.fpcore
tests/scripts/test-export.out.txt

This PR refactors compiler code, cleans up compiler output, and fixes test generation.
-  removes redundant casts
-  trims redundant parentheses in output
-  nested `if` statements export with `if`, `else if`, `else` branches

Cleanup exporting and test generation

---

.github/workflows/test.yml

Github Actions recently changed how they wanted you to add to the system path, and that broke our CI. This PR fixes it.

Change the test runner to fix the CI

---

.github/workflows/test.yml
export.rkt
infra/test-common.rkt
infra/test-core2fptaylor.rkt
src/core2fptaylor.rkt
src/fpcore-extra.rkt
src/imperative.rkt
src/range-analysis.rkt
tests/metadata.fpcore
tests/sanity/numbers.fpcore
tests/scripts/test-export.out.txt
tests/scripts/test-transform.out.txt

A new FPTaylor compiler which supports precision annotations. This new compiler is based on the Sollya compiler.
I also updated the version of FPTaylor in tests.
Other changes:
- Using `exact-max` and `exact-min` in `range-analysis.rkt`.
- `imperative.rkt`: the precision of annotated arguments is added to the context. I initially added the following test case:
```racket
(FPCore ((! :precision binary32 x))
:name "monadius args"
:description "v should have the same precision as x"
:precision binary64
:pre (<= 1 x 20)
(let ((v x)) (+ v v)))
```
But Z3 and CakeML tests did not pass this test case. So this test case is not included in the PR.

A new FPTaylor compiler

---

benchmarks/salsa.fpcore

I've traced this precondition and can't seem to find a justification for it. It also doesn't make sense (it is literally impossible to make true!). Striking it.
Thank you Shoaib Kamil for finding it!

Fix bug in Iterative Gram-Schmidt benchmark

---

src/core2c.rkt

This PR fixes #97 by adding an "h" language, which just generates C headers without the C bodies. The code change is minimal and should be easy to maintain going forward. If we have other languages with header files, we should do the same for those (`*.mli` files?).

Generate C header files

---

infra/test-core2ocaml.rkt
src/core2fptaylor.rkt
src/core2java.rkt
src/core2ocaml.rkt
tests/sanity/ops.fpcore

In most languages (compared to C), the `fmin` and `fmax` functions have different behavior when it comes to `NaN` arguments. The C99 standard states that these functions treat `NaN` as missing data, so it will return the other argument if they encounter a `NaN`. Most languages prefer to return `NaN` if any argument is `NaN`. This PR just adds a few sanity tests to check this behavior, and fixes some compilers that did not translate this correctly.

Adds sanity tests for fmin/fmax

---

src/core2ocaml.rkt
src/ml.rkt
tests/sanity/bool-ops.fpcore

This PR adds missing boolean operator (sanity) tests and fixes the compilers that fail these new tests.
- `NaN` != `NaN`
- N-ary comparators, e.g. `(> x y z)` (3-ary is good enough)
- N-ary logical connectives, e.g. `(and x y z)` (3-ary is good enough)

Add missing boolean operator tests

---

.github/workflows/test.yml

Building Daisy fails in CI due to git authentication issues within GitHub Actions (exact cause unknown). A workaround has been added to successfully build Daisy and run related jobs. The workaround will be removed once the default Daisy build process is updated to work in Actions.

Workaround for running Daisy in GitHub Actions

---

.github/workflows/test.yml
Makefile
export.rkt
infra/test-core2rust.rkt
src/core2rust.rkt
src/imperative.rkt

This PR adds supports for exporting to Rust, and corresponding tests.
Things to note:
- Rust supports both `f32` and `f64` for computations as well as storage. However, this PR only adds `binary64`/`f64` support.
- [Rust supports `fdim` as `{f32, f64}::abs_sub` except it is deprecated](https://doc.rust-lang.org/std/primitive.f64.html#method.abs_sub) so I didn't add it.
- I added some directives to ignore many compiler warnings, with the exception of unused variables/assignments (in my opinion, they represent FPCore programming errors). Let me know if those warnings should be silenced too.
- A subset of `asinh`/`acosh` tests (really large inputs) fail due to precision issues with Rust's implementation of them. The failures are apparently "suppressed"
- I was introduced to the codebase a …

Add Rust compiler support

---

.github/workflows/test.yml
Makefile
src/core2c.rkt
src/core2cakeml.rkt
src/core2fortran03.rkt
src/core2fptaylor.rkt
src/core2gappa.rkt
src/core2go.rkt
src/core2haskell.rkt
src/core2java.rkt
src/core2js.rkt
src/core2julia.rkt
src/core2matlab.rkt
src/core2ocaml.rkt
src/core2python.rkt
src/core2rust.rkt
src/core2scala.rkt
src/core2smtlib2.rkt
src/core2sollya.rkt
src/core2tex.rkt
src/core2wls.rkt
src/supported.rkt

This PR addresses why #115 is failing. Tensor benchmarks should not be valid in any of our current benchmarks. Also fixes Julia in CI due to OS version changes in GitHub Actions.

Disable tensor tests

---

benchmarks/salsa.fpcore

This PR fixes #116 by specifying `x0` as an input to the Newton-Raphson benchmark.
This is tricky change because it changes the semantics of this benchmark if non-default inputs are used. Alternatively, I'm open to a change where we remove the input entirely, so that this benchmark just specifies a loop. This better matches the [original](https://github.com/FPBench/FPBench/blob/b054f2cc87fa9acfe985c84bbbaff2211bf7d650/originals/loop-tests/Newton-Raphson's%20Method) version of this benchmark.

Fix #116 by specifying input to Newton-Raphson

---

src/core2tex.rkt

This pull requests fixes the issues with underscores in Tex output for FPCore expressions.
See related [issue](https://github.com/herbie-fp/herbie/issues/668) in [herbie](github.com/herbie-fp/herbie).

Fix underscore escaping for variables in Tex output

---

.gitignore
Makefile
main.rkt

This PR adds a `make` target (`make distribute`) for creating an executable for FPBench.
The resulting executable behaves as specified in the design document for tools that already exist (features such as filtering etc. are still unimplemented). 
The notable exceptions are the inclusion of the subcommand `export`, which is an alias for `compile`; and the inclusion of the subcommand `evaluate`, which runs the evaluate tool.
This mechanism has only been tested through WSL. 
The make script is directly ripped from Herbie's `make distribute` target.

Initial Launcher

---

.github/workflows/test.yml
infra/test-core2julia.rkt

The startup and pre-compilation costs of julia are high,
so for simple computations you can skip the pre-compilation and optimization.
```
Baseline:
santity:    88s
benchmarks: 604s
binary32:   724s
binary64:   721s
Pr:
santity:    29s
benchmarks: 216s
binary32:   269s
binary64:   301s
```

ci: speedup julia test & setup ci for pr

---

README.md
tools.md

The tool documentation used to live online, but that just made it hard to edit and out of date. This PR moves the tool documentation to `tools.md` in this repository. I did an auto-conversion using Pandoc, and then cleaned that up along with some bug fixes.

Move the tool documentation to this repository

---

.github/workflows/test.yml
README.md

This PR fixes the build status badge and fixes the typo of language in the `test.yml` file.

Fix build status badge and typo in `test.yml`

---

infra/test-core2julia.rkt
src/core2julia.rkt

@AYadrov noticed that the Julia compiler can create exponential-size outputs if it compiles something with nested `fmin` and `fmax` operators; this PR fixes this by defining helper functions.

Fix exponential-size Julia output for nested min/max operators

---

.gitignore
src/core2fortran03.rkt

Same as #134, Fortran also can output exponential-size programs with nested `fmin` and `fmax` operators.
This PR fixes this by introducing helper functions.

Fixing exponential-size Fortran output programs for nested min/max operators 

---

infra/test-core2fortran03.rkt
src/core2fortran03.rkt

PR #135 added a Fortran header but incorrectly added it to the compiled programs instead of as a proper header.

Make `core2fortran` use headers properly so Herbie tests work

---

www/index.html

This will make `https://fpbench.github.io/fpbench` the official website for the FPBench benchmark suite.

Fix the first link & rename page

---

.github/workflows/test.yml

Our CI stopped working because it seems like the old version of `setup-ocaml` no longer runs. I took the chance to upgrade our OCaml version too.

Upgrade `ocaml/setup-ocaml` to v3 and OCaml itself to v5
